NOME DOS EMPREGADOS QUE TEM DEPENDENTES COM O MESMO PRIMEIRO NOME DELES

SELECT FNAME FROM EMPLOYEE E 
INNER JOIN DEPENDENT D ON E.SSN = D.ESSN
WHERE FNAME LIKE DEPENDENT_NAME%

NOME DOS EMPREGADOS SUPERVISIONADOS POR FRANKLIN WONG

SELECT FNAME || ' ' || LNAME
FROM EMPLOYEE E1
INNER JOIN EMPLOYEE E2 ON E1.SUPERSSN = E2.SSN
WHERE E2.FNAME || ' ' || E2.LNAME = 'FRANKLIN WONG'

NOME DOS EMPREGADOS QUE TRABALHAM EM TODOS PROJETOS

WITH T1 AS (
SELECT 
FROM EMPLOYEE E
LEFT JOIN WORKS_ON W ON E.SSN = W.ESSN
WHERE W.HOURS = NULL )

SELECT E.FNAME
FROM EMPLOYEE E
WHERE E.SSN NOT IN (SELECT T1.SSN FROM T1)

EMPREGADOS QUE PROJETO EH EM HOUSTON MAS DEPARTAMENTO NAO EH EM HOUSTON

ERRADO! (
SELECT FNAME  || ' ' || LNAME
FROM EMPLOYEE E
INNER JOIN DEPT_LOCATIONS DL ON E.DNO = DL.DNUMBER
INNER JOIN WORKS_ON W ON E.SSN = W.ESSN
INNER JOIN PROJECT P ON W.PNO = P.PNUMBER
WHERE PLOCATION = 'HOUSTON' AND DLOCATION <> 'HOUSTON'
)

CERTO (
WITH T1 AS ( SELECT DL.DNUMBER
FROM DEPT_LOCATIONS DL
WHERE DL.DLOCATION = 'HOUSTON'
)

SELECT E.FNAME, E.ADRESS
FROM EMPLOYEE E
INNER JOIN WORKS_ON W ON 
INNER JOIN PROJECT P ON
WHERE E.DNO NOT IN (SELECT D.NUMBER FROM T1) AND P.LOC='HOUSTON'
