6.17 a
WITH T1 AS (
	SELECT FLIGHT_NUMBER, MIN(SCHEDULED_DEPARTURE_TIME) AS MI, MAX(SCHEDULED_DEPARTURE_TIME) AS MA
	FROM FLIGHT_LEG
	GROUP BY FLIGHT_NUMBER
)
SELECT T1.FLIGHT_NUMBER, A1.NAME, A2.NAME FROM T1
INNER JOIN FLIGHT_LEG AS T2 ON T2.SCHEDULED_DEPARTURE_TIME = T1.MI AND T1.FLIGHT_NUMBER = T2.FLIGHT_NUMBER
INNER JOIN FLIGHT_LEG AS T3 ON T3.SCHEDULED_DEPARTURE_TIME = T1.MA AND T1.FLIGHT_NUMBER = T3.FLIGHT_NUMBER
INNER JOIN AIRPORT A1 ON AIRPORT_CODE = T1.DEPARTURE_AIRPORT_CODE
INNER JOIN AIRPORT A2 ON AIRPORT_CODE = T3.ARRIVAL_AIRPORT_CODE

6.17 c
USANDO T1 E T2 DA LETRA A
WITH 
	T1(NV, "MIN", "MAX") AS (....)
	T2(NV, PART, CHEG, WEEKDAYS) AS (....)
	ORIG AS (SELECT AIRPORT_CODE FROM AIRPORT WHERE CITY = 'HOUSTON')
	DEST AS (....)
	SEL1 AS (SELECT * FROM VOOS WHERE VOOS.PART IN (SELECT * FROM ORIG) AND VOOS.DEST IN (SELECT * FROM DEST)
	SEL2 AS (
	SELECT FROM SEL 1 UNION .... FROM SEL2
